### ISSUE TITLE
Package won't install via PackageControl with message "Successfully installed"

### ISSUE THREAD

**Issue by dskarasev** [fitnr/SublimeCSSTidy#25]
The package is not installed via PackageControl and a successful installation is reported. Csstidy folder is not created in the Packages folder. An error is thrown at startup:

```
b''
Command sent to Tidy:
php -f /Users/dkarasev/Library/Application Support/Sublime Text 3/Packages/CSSTidy/csstidy.php --
```

**Comment by fitnr** [comment]
It looks like is installed, since this is a message from the package. WIthout more information I can't debug this.
